spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

---

spring:
  config:
    activate:
      on-profile: test
  mongodb:
    embedded:
      version: 3.8.4


---

spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local