spring:
  profiles:
    active: dev

server:
  port: 8081
---

spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
---

spring:
  profiles: test
  mongodb:
    embedded:
      version: 4.0.21

